# Generated by Django 5.2.17 on 2026-09-05 14:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='記錄日期')),
                ('did_today', models.TextField(blank=True, default='', verbose_name='今天做了什麼')),
                ('learned_today', models.TextField(blank=True, default='', verbose_name='今天學到了什麼')),
                ('failed_today', models.TextField(blank=True, default='', verbose_name='哪裡失敗了')),
                ('resistance_today', models.TextField(blank=True, default='', verbose_name='為什麼不想做 / 當下心情')),
                ('raw_content', models.TextField(blank=True, default='', verbose_name='自由速寫純文字')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後修改時間')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='goals.anchorgoal', verbose_name='當前方向')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '手帳日誌',
                'verbose_name_plural': '手帳日誌',
                'ordering': ['-entry_date'],
                'unique_together': {('user', 'entry_date')},
            },
        ),
        migrations.CreateModel(
            name='SoulReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, default='', verbose_name='今日簡記 (AI幫忙整理的客觀記錄)')),
                ('blindspot', models.TextField(blank=True, default='', verbose_name='頁緣觀察 (照見盲點與真實)')),
                ('soul_question', models.TextField(blank=True, default='', verbose_name='靈魂提問')),
                ('source', models.CharField(default='default_pool', max_length=20, verbose_name='來源 (gemini / default_pool)')),
                ('user_answer', models.TextField(blank=True, default='', verbose_name='今晚隨筆筆記/回答')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成時間')),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reflection', to='journal.journalentry')),
            ],
            options={
                'verbose_name': '靈魂反思與提問',
                'verbose_name_plural': '靈魂反思與提問',
            },
        ),
    ]
