# Generated by Django 6.1 on 2026-08-15 11:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='群組主題')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_collections', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '自訂主題群組',
                'verbose_name_plural': '自訂主題群組清單',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FutureLogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_month', models.DateField(verbose_name='目標月份 (如 2026-10-01)')),
                ('content', models.CharField(max_length=300, verbose_name='預定事項')),
                ('is_migrated', models.BooleanField(default=False, verbose_name='是否已遷移至當月月誌')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_log_items', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '未來誌項目',
                'verbose_name_plural': '未來誌項目清單',
                'ordering': ['target_month', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='日誌日期')),
                ('am_intent', models.CharField(blank=True, max_length=200, verbose_name='晨間意圖 / 今日焦點 (AM Intent)')),
                ('pm_reflection', models.TextField(blank=True, verbose_name='晚間省思 / 今日覺察 (PM Reflection)')),
                ('mood_score', models.PositiveSmallIntegerField(default=3, verbose_name='狀態評分 (1-5)')),
                ('raw_input', models.TextField(blank=True, verbose_name='快速速記原始文字')),
                ('ai_summary', models.TextField(blank=True, verbose_name='AI 整理摘要')),
                ('ai_reflection', models.TextField(blank=True, verbose_name='AI 溫暖反思')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='是否已完成晚間省思')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '每日日誌',
                'verbose_name_plural': '每日日誌清單',
                'ordering': ['-entry_date'],
                'unique_together': {('user', 'entry_date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='年份')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='月份')),
                ('month_focus', models.CharField(blank=True, max_length=200, verbose_name='當月核心焦點')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_logs', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '月誌',
                'verbose_name_plural': '月誌清單',
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='BulletItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('task', '• 任務 (Task)'), ('note', '- 筆記 (Note)'), ('event', '○ 事件 (Event)'), ('reflection', '★ 反思 (Reflection)'), ('obstacle', '! 阻礙 (Obstacle)')], default='task', max_length=20, verbose_name='項目類型')),
                ('status', models.CharField(choices=[('open', '• 進行中 (Open)'), ('completed', 'x 已完成 (Completed)'), ('migrated', '> 遷移至明日/下月 (Migrated)'), ('scheduled', '< 排程至未來誌 (Scheduled)'), ('cancelled', '— 劃掉取消 (Irrelevant)')], default='open', max_length=20, verbose_name='子彈狀態')),
                ('signifier', models.CharField(choices=[('none', '無'), ('priority', '* 優先重要 (*)'), ('inspiration', '! 靈感 (!)')], default='none', max_length=20, verbose_name='符號標記')),
                ('content', models.CharField(max_length=500, verbose_name='項目內容')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_bullets', to='goals.goalproject', verbose_name='關聯目標')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bullets', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_bullets', to='journal.customcollection', verbose_name='關聯群組')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='journal.journalentry', verbose_name='所屬日誌')),
                ('monthly_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_bullets', to='journal.monthlylog', verbose_name='所屬月誌')),
            ],
            options={
                'verbose_name': '子彈項目',
                'verbose_name_plural': '子彈項目清單',
                'ordering': ['order_index', 'id'],
            },
        ),
    ]
