# Generated by Django 5.2.17 on 2026-09-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(blank=True, default='chaos', max_length=20, verbose_name='今日心情戳記'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='weather',
            field=models.CharField(blank=True, default='sunny', max_length=20, verbose_name='今日天氣'),
        ),
    ]
