# Generated by Django 5.2.17 on 2026-09-05 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnchorGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='目標方向')),
                ('why', models.TextField(blank=True, default='', verbose_name='初心與期待')),
                ('is_active', models.BooleanField(default=True, verbose_name='當前焦點目標')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='封存時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchor_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '錨點目標',
                'verbose_name_plural': '錨點目標',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
