# Generated by Django 6.1 on 2026-08-15 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='目標名稱')),
                ('why_statement', models.TextField(blank=True, help_text='為什麼這個目標對你至關重要？', verbose_name='核心動機 (Why)')),
                ('timeframe', models.CharField(choices=[('5_years', '5 年長期願景 (5 Years)'), ('4_months', '4 個月中期衝刺 (4 Months)'), ('3_weeks', '3 週短期專案 (3 Weeks)'), ('2_days', '2 天具體行動 (2 Days)'), ('1_hour', '1 小時微小起步 (1 Hour)')], default='4_months', max_length=15, verbose_name='時間跨度')),
                ('status', models.CharField(choices=[('active', '進行中'), ('completed', '已達成'), ('archived', '已歸檔')], default='active', max_length=15, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_goals', to='inventory.mentalinventoryitem', verbose_name='關聯人生清單')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '核心目標',
                'verbose_name_plural': '核心目標清單',
                'ordering': ['-status', 'created_at'],
            },
        ),
    ]
