# Generated by Django 6.1 on 2026-08-15 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_type', models.CharField(choices=[('doing', '我正在做的事 (What I am doing)'), ('should_do', '我應該做的事 (What I should do)'), ('want_to_do', '我想做的事 (What I want to do)')], default='doing', max_length=20, verbose_name='盤點維度')),
                ('content', models.CharField(max_length=250, verbose_name='項目內容')),
                ('test_status', models.CharField(choices=[('pending', '待篩選'), ('kept', '保留 (重要或有意義)'), ('discarded', '劃掉丟棄 (不重要且無意義)')], default='pending', max_length=15, verbose_name='篩選測試結果')),
                ('category', models.CharField(choices=[('none', '未分類'), ('obligation', '責任 (Obligations - 必須做的)'), ('goal', '目標 (Goals - 真正追求的)')], default='none', max_length=15, verbose_name='分類屬性')),
                ('is_focus', models.BooleanField(db_index=True, default=False, verbose_name='是否為當前最在意的核心項目 (Focus)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '思想盤點項目',
                'verbose_name_plural': '思想盤點項目清單',
                'ordering': ['inventory_type', '-is_focus', 'id'],
            },
        ),
    ]
