# Generated by Django 6.1 on 2026-08-15 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISummaryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('weekly', '週報 (Weekly Digest)'), ('monthly', '月報 (Monthly Retrospective)')], db_index=True, max_length=10, verbose_name='報表類型')),
                ('start_date', models.DateField(db_index=True, verbose_name='統計起始日')),
                ('end_date', models.DateField(db_index=True, verbose_name='統計結束日')),
                ('title', models.CharField(max_length=150, verbose_name='報告標題')),
                ('statistics', models.JSONField(blank=True, default=dict, verbose_name='統計分析數據 (JSON)')),
                ('core_learnings', models.TextField(verbose_name='核心收穫與累積')),
                ('recurring_obstacles', models.TextField(verbose_name='重複出現的盲點與混亂')),
                ('growth_advice', models.TextField(verbose_name='AI 下一階段行動建議')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_reports', to=settings.AUTH_USER_MODEL, verbose_name='所屬使用者')),
            ],
            options={
                'verbose_name': 'AI 週期報告',
                'verbose_name_plural': 'AI 週期報告清單',
                'ordering': ['-end_date'],
            },
        ),
    ]
